spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imbd
    username: root
    password: Naveen@270
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        # generate_statistics: true
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file: logs/application-debug.log
  pattern:
#    console: "%d %-5level %logger : %msg%n"
    console: "%date  %highlight(%-5level) [%12.12thread] %yellow(%-40.40logger{40}) : %msg %n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO

#hibernate.generate_statistics=true
